from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DashboardWindows(object):

    def setupUi(self, DashboardWindows):
        DashboardWindows.setObjectName("DashboardWindows")
        DashboardWindows.resize(1150, 705)
        self.centralwidget = QtWidgets.QWidget(DashboardWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(221, 142, 581, 71))
        self.progressBar.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.progressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(220, 270, 581, 71))
        self.progressBar_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.progressBar_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(220, 390, 581, 71))
        self.progressBar_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.progressBar_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(220, 510, 581, 71))
        self.progressBar_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.progressBar_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 431, 111))
        self.label.setStyleSheet("font: 30pt \"Kanit\";")
        self.label.setObjectName("label")
        self.btnLogout = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogout.setGeometry(QtCore.QRect(970, 30, 141, 51))
        self.btnLogout.setStyleSheet("font: 20pt \"Kanit\";\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")

        self.btnLogout.setObjectName("btnLogout")
        self.btnLogout.clicked.connect(self.logout)

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 132, 131, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dial = QtWidgets.QDial(self.layoutWidget)
        self.dial.setMaximum(100)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.verticalLayout.addWidget(self.dial)
        self.dial_2 = QtWidgets.QDial(self.layoutWidget)
        self.dial_2.setMaximum(100)
        self.dial_2.setNotchesVisible(True)
        self.dial_2.setObjectName("dial_2")
        self.verticalLayout.addWidget(self.dial_2)
        self.dial_3 = QtWidgets.QDial(self.layoutWidget)
        self.dial_3.setMaximum(100)
        self.dial_3.setNotchesVisible(True)
        self.dial_3.setObjectName("dial_3")
        self.verticalLayout.addWidget(self.dial_3)
        self.dial_4 = QtWidgets.QDial(self.layoutWidget)
        self.dial_4.setMaximum(100)
        self.dial_4.setNotchesVisible(True)
        self.dial_4.setObjectName("dial_4")
        self.verticalLayout.addWidget(self.dial_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(840, 130, 271, 471))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_2.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_2.addWidget(self.lcdNumber_2)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_2.addWidget(self.lcdNumber_3)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_2.addWidget(self.lcdNumber_4)
        DashboardWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 26))
        self.menubar.setObjectName("menubar")
        DashboardWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardWindows)
        self.statusbar.setObjectName("statusbar")
        DashboardWindows.setStatusBar(self.statusbar)

        self.retranslateUi(DashboardWindows)
        self.dial.valueChanged['int'].connect(self.progressBar.setValue)
        self.dial.valueChanged['int'].connect(self.lcdNumber.display)
        self.dial_2.valueChanged['int'].connect(self.progressBar_2.setValue)
        self.dial_2.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.dial_3.valueChanged['int'].connect(self.progressBar_3.setValue)
        self.dial_3.valueChanged['int'].connect(self.lcdNumber_3.display)
        self.dial_4.valueChanged['int'].connect(self.progressBar_4.setValue)
        self.dial_4.valueChanged['int'].connect(self.lcdNumber_4.display)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindows)

    def retranslateUi(self, DashboardWindows):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindows.setWindowTitle(_translate("DashboardWindows", "Dashboard"))
        self.label.setText(_translate("DashboardWindows", "Dashbaord Control"))
        self.btnLogout.setText(_translate("DashboardWindows", "Logout"))

    def logout(self):
        DashboardWindows.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardWindows = QtWidgets.QMainWindow()
    ui = Ui_DashboardWindows()
    ui.setupUi(DashboardWindows)
    DashboardWindows.show()
    sys.exit(app.exec_())
